
# Kernel Fabric Interface Provider - IBV (InfiniBand Verbs provider)

MOD=kfip_ibv

obj-m := $(MOD).o

$(MOD)-y := main.o enosys.o

ccflags-y := -I$(src)
ccflags-y += -I$(src)/../../include

ccflags-n += -DCONFIG_KFI_DEBUG=1
